// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RequestsService.Infrastructure;

#nullable disable

namespace RequestsService.Migrations
{
    [DbContext(typeof(RequestDbContext))]
    [Migration("20260105195313_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RequestsService.Domain.Entities.RequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ManagerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Requests");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = new Guid("c5209f70-7106-4166-b1c1-36a07693129f"),
                            CreatedAt = new DateTime(2026, 1, 5, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Тестовое описание 1",
                            ManagerId = new Guid("00000000-0000-0000-0000-000000000000"),
                            Status = 0,
                            Title = "Тестовая заявка 1"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = new Guid("c5209f70-7106-4166-b1c1-36a07693129f"),
                            CreatedAt = new DateTime(2026, 1, 3, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Тестовое описание 2",
                            ManagerId = new Guid("f4c3952d-d633-4850-9042-8af385ef2253"),
                            Status = 3,
                            Title = "Тестовая заявка 2"
                        });
                });

            modelBuilder.Entity("RequestsService.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("JobTitle")
                        .HasColumnType("integer");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c5209f70-7106-4166-b1c1-36a07693129f"),
                            Email = "engineer@job.ru",
                            FullName = "Иванов Иван Иванович",
                            JobTitle = 0,
                            Phone = "+79999999999"
                        },
                        new
                        {
                            Id = new Guid("f4c3952d-d633-4850-9042-8af385ef2253"),
                            Email = "manager@job.ru",
                            FullName = "Петров Петр Петрович",
                            JobTitle = 1,
                            Phone = "+78888888888"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
